// Code generated by "stringer -type=Action"; DO NOT EDIT.

package move

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Quit-0]
	_ = x[Flip-1]
	_ = x[Take-2]
	_ = x[Move-3]
}

const _Action_name = "QuitFlipTakeMove"

var _Action_index = [...]uint8{0, 4, 8, 12, 16}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
